<h2>
Applied Data Science Capstone - Week 3, Question 2

<h4>
The Code from Question 1:

In [6]:
import pandas as pd
import numpy as np
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
html = urlopen(url)
soup = BeautifulSoup(html, 'lxml')
rows = soup.find_all('tr')
list_rows = []
for row in rows:
    cells = row.find_all('td')
    str_cells = str(cells)
    clean = re.compile('<.*?>')
    clean2 = (re.sub(clean, '',str_cells))
    list_rows.append(clean2)
df = pd.DataFrame(list_rows)
df1 = df[0].str.split(',', expand=True)
df1[0] = df1[0].str.strip('[')
for i in range (30):
    df1[i] = df1[i].str.strip('\n')
    df1[i] = df1[i].str.strip('\n]')
df2 = df1[df1[1] != " Not assigned"]
df2 = df2.drop([0],axis=0)
df2 = df2[:-4]
df2 = df2.reset_index(drop=True)
df2['Neighborhood'] = ""
for i in range (31):
    for j in range (103):
        if i > 1 and df2[i][j] != None:
            if df2['Neighborhood'][j]=="":
                df2['Neighborhood'][j]= df2[i][j]
            else:
                df2['Neighborhood'][j]=df2['Neighborhood'][j]+ ', ' + df2[i][j]
df2.drop(df2.iloc[:, 2:31], inplace = True, axis = 1)
df2.columns = ['Postal Code','Borough','Neighborhood']
df2.head()

,Postal Code,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"

<h4>
I couldn't get the geocoder to work reliably, so I used the .csv file to make a dataframe:

In [11]:
Long_Lat = pd.read_csv("Geospatial_Coordinates.csv")
Long_Lat.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

<h4>
Then I merged the dataframes based on the Postal Code:

In [13]:
merge_Toronto = pd.merge(df2, Long_Lat, on='Postal Code')
merge_Toronto.head()

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494